name: OWASP ZAP Integration with Github Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          cmd_options: '-a'
      
      - name: Create Issue
        if: failure()  # Only try to create an issue if the scan fails
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "OWASP ZAP Scan Results"
          content-filepath: ./zap_report.md  # Path to your scan report
